name: Run Psalm

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - if: ${{ github.event_name == 'pull_request' }}
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          composer_require_dev: true

      - if: ${{ github.event_name != 'pull_request' }}
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          composer_require_dev: true
          args: --shepherd