name: Run Psalm

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          composer_require_dev: true